import type { ActorProfile } from "./types.ts";

export const ACTORS: ActorProfile[] = [
  {
    id: "marija-serifovic",
    displayName: "Marija Šerifović",
    aliases: ["Marija Serifovic", "Serifovic", "Šerifović", "Serifovicka"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/marija-serifovic.jpg",
  },
  {
    id: "zeljko-joksimovic",
    displayName: "Željko Joksimović",
    aliases: ["Zeljko Joksimovic", "Joksimovic", "Željko", "Zeljko"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/zeljko-joksimovic.jpg",
  },
  {
    id: "konstrakta",
    displayName: "Konstrakta",
    aliases: ["Ana Đurić", "Ana Djuric", "Ana Ignjatovic"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/konstrakta.jpg",
  },
  {
    id: "sanja-vucic",
    displayName: "Sanja Vučić",
    aliases: ["Sanja Vucic", "Sanja", "Vučić", "Vucic"],
    difficulty: "Hard",
    difficultyMultiplier: 1.8,
    portrait: "/actors/sanja-vucic.jpg",
  },
  {
    id: "djordje-balasevic",
    displayName: "Đorđe Balašević",
    aliases: ["Djordje Balasevic", "Đole Balašević", "Djole Balasevic", "Balasevic"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/djordje-balasevic.jpg",
  },
  {
    id: "dino-merlin",
    displayName: "Dino Merlin",
    aliases: ["Edin Dervišhalidović", "Edin DervisHalidovic", "Merlin"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/dino-merlin.jpg",
  },
  {
    id: "goran-bregovic",
    displayName: "Goran Bregović",
    aliases: ["Goran Bregovic", "Bregović", "Bregovic"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/goran-bregovic.jpg",
  },
  {
    id: "zdravko-colic",
    displayName: "Zdravko Čolić",
    aliases: ["Zdravko Colic", "Čola", "Cola", "Čolić", "Colic"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/zdravko-colic.jpg",
  },
  {
    id: "amira-medunjanin",
    displayName: "Amira Medunjanin",
    aliases: ["Amira", "Medunjanin", "Amira Dedić", "Amira Dedic"],
    difficulty: "Hard",
    difficultyMultiplier: 1.8,
    portrait: "/actors/amira-medunjanin.jpg",
  },
  {
    id: "haris-dzinovic",
    displayName: "Haris Džinović",
    aliases: ["Haris Dzinovic", "Haris", "Džinović", "Dzinovic"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/haris-dzinovic.jpg",
  },
  {
    id: "sergej-cetkovic",
    displayName: "Sergej Ćetković",
    aliases: ["Sergej Cetkovic", "Sergej", "Ćetković", "Cetkovic"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/sergej-cetkovic.jpg",
  },
  {
    id: "rambo-amadeus",
    displayName: "Rambo Amadeus",
    aliases: ["Antonije Pušić", "Antonije Pusic", "Rambo"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/rambo-amadeus.jpg",
  },
  {
    id: "knez",
    displayName: "Knez",
    aliases: ["Nenad Knežević", "Nenad Knezevic", "Knez Montenegro"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/knez.jpg",
  },
  {
    id: "andrea-demirovic",
    displayName: "Andrea Demirović",
    aliases: ["Andrea Demirovic", "Andrea", "Demirović", "Demirovic"],
    difficulty: "Hard",
    difficultyMultiplier: 1.8,
    portrait: "/actors/andrea-demirovic.jpg",
  },
  {
    id: "slavko-kalezic",
    displayName: "Slavko Kalezić",
    aliases: ["Slavko Kalezic", "Slavko", "Kalezić", "Kalezic"],
    difficulty: "Hard",
    difficultyMultiplier: 1.8,
    portrait: "/actors/slavko-kalezic.jpg",
  },
  {
    id: "severina",
    displayName: "Severina",
    aliases: ["Severina Vučković", "Severina Vuckovic", "Seve"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/severina.jpg",
  },
  {
    id: "oliver-dragojevic",
    displayName: "Oliver Dragojević",
    aliases: ["Oliver Dragojevic", "Oliver", "Dragojević", "Dragojevic"],
    difficulty: "Easy",
    difficultyMultiplier: 1,
    portrait: "/actors/oliver-dragojevic.jpg",
  },
  {
    id: "nina-badric",
    displayName: "Nina Badrić",
    aliases: ["Nina Badric", "Nina", "Badrić", "Badric"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/nina-badric.jpg",
  },
  {
    id: "josipa-lisac",
    displayName: "Josipa Lisac",
    aliases: ["Josipa", "Lisac"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/josipa-lisac.jpg",
  },
  {
    id: "tony-cetinski",
    displayName: "Tony Cetinski",
    aliases: ["Toni Cetinski", "Anthony Cetinski", "Cetinski"],
    difficulty: "Medium",
    difficultyMultiplier: 1.4,
    portrait: "/actors/tony-cetinski.jpg",
  },
];
